      barcode:{ "CofC Terminal Case 2": "", 
               "CofC Terminal Case 1": "", 
               "2012_NAICS": "112519", 
               "Customer Product": "RP", 
               "Dictionary Position Description": "These companies catch and sell freshwater fish and seafood. They sell through food retailers.",
               "CofC Final Resource 2": "",
                "Enterprise Locus": "2.2.2 E3i", 
                "Customer Locus": "1.3.2 F", 
                "CofC Department Locus": "", 
                "Final Resource 1": "E4i 2.2.2 F", 
                "Final Resource 2": "", 
                "Customer of Customer Locus": "", 
                "Co-Customer Temporal": "", 
                "Customer Type": "Consumers",
                 "Relationship Type": "", 
                 "Department Locus": "DivA DivA",
                "Co-Customer Product": "",
                "Co-Customer Type": "", 
                "Intermediary 2 Type": "",
                "Co-Customer Locus": "", 
                "CofC Constituent Resource 2": "", 
                "CofC Product": "", 
                "Dictionary Position Title": "Fish and Seafood", 
                "Work Group 2": "", 
                "AD": "818.5", 
                "Intermediary 1 Locus": "(A4ii) 3.1.2 EDivA", 
                "Work Group 1": "DivA DivA", 
                "Constituent Resource 1": "E3i 1.3.2 E4DivA", 
                "Constituent Resource 2": "", 
                "CofC Type": "", 
                "Terminal Case 2": "", 
                "Terminal Case 1": "DivM", 
                "Customer Relationship": "", 
                "Customer Temporal": "First", 
                "CofC Constituent Resource 1": "", 
                "Enterprise Product": "RP", 
                "Process": "In-house", 
                "Intermediary 2 Locus": "", 
                "CofC Work Group 1": "", 
                "CofC Final Resource 1": "", 
                "2012_Title": "Other Aquaculture", 
                "CofC Work Group 2": "", 
                "Intermediary 1 Type": "With Inventory", 
                "Product Line": "Main"}